name: Bishapay Prod Pipeline

on:
  push:
    branches:
      - master

jobs:
  run_test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - run: echo "Starting execute unit test"
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Maven Verify
        run: mvn clean verify
#      - name: Login to docker hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build docker image
#        uses: docker/build-push-action@v2
#        with:
#          file: unit-test.dockerfile
#          context: .
#          push: true
#          tags: hamidbae/capstone14-be-alterra-coverage-sit:latest
  build:
    name: Build
    runs-on: ubuntu-18.04
    needs: run_test
    steps:
      - run: echo "Starting build package"
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Maven Build
        run: mvn clean package -Dmaven.test.skip=true
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hamidbae/capstone14-be-alterra:latest
  deployment:
    name: Deploy
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - run: echo "Starting deploy container"
      - uses: actions/checkout@v3
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST_PROD }}
          port: 22
          username: ${{ secrets.EC2_SSH_USERNAME_PROD }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY_PROD }}
          script: |
            docker stop capstone14-be
            docker rmi hamidbae/capstone14-be-alterra:latest
            docker pull hamidbae/capstone14-be-alterra:latest
            docker run -d --rm --name capstone14-be -p 80:8080 --env --env-file=.env.prod --network c14-network hamidbae/capstone14-be-alterra:latest